export default PRNG64;
/**
 * 64 bit modification of PRNG class.
 * @class
 * @extends {PRNG}
 * @param {number | bigint} max -> Max number that can be generated by this generator.
 * @param {number | bigint} seed -> Initial seed.
 */
declare class PRNG64 extends PRNG {
}
import PRNG from "./PRNG.js";
